config/routes.rb
Rails.application.routes.draw do

   root 'quotes#random_quote'

  resources :quotes
  resources :imports
  get 'signup', to: 'users#new'
  resources :users, ecxept: [:new]

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :user
  validates :quote, :source, :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :quotes
  has_secure_password
  before_save { self.email = email.downcase }
  validates :name, presence: true, uniqueness: {case_sensitive: false}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email , presence: true, uniqueness: {case_sensitive: false}, format: { with:  VALID_EMAIL_REGEX }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_login

      if !logged_in?
        flash[:notice] = "You must be logged in to have permission"
        redirect_to login_path
      end

  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController

def new

end

def create
  uri = URI('http://quotesondesign.com/wp-json/posts?filter[orderby]=rand&filter[posts_per_page]=20')

  response = Net::HTTP.get(uri)
  json_quotes = JSON.parse(response)

  @quotes = []
  json_quotes.each do |quote|

   @quotes << Quote.create(source: quote['title'], quote:  ActionView::Base.full_sanitizer.sanitize(quote['content']), user_id: User.first.id )

  end
end




end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:edit, :update, :show, :destroy]
  before_action :require_login, except: [ :index, :show, :random_quote ]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @quotes = Quote.all.order("created_at DESC")
  end

  def new
    @quote = Quote.new
  end

  def edit

  end

  def create
    @quote = Quote.new(quote_params)
    @quote.user = current_user
    if @quote.save
      flash[:success] = "Youre created succesfully a new Quote!!"
      redirect_to quote_path(@quote)
    else
      render 'new'
    end

  end

  def update

    if @quote.update(quote_params)
      flash[:notice] = "Your Quote is succesfully updated"
      redirect_to quote_path(@quote)
    else
      render 'edit'
    end
  end

  def show

  end

  def destroy

    @quote.destroy
    flash[:notice] = "Quote is succesfully deleted!"
    redirect_to quotes_path
  end

  def random_quote
    @quote = Quote.order("RANDOM()").first
  end

  private

  def set_quote
    @quote = Quote.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:quote, :source)
  end

  def require_same_user
    if current_user != @quote.user
      flash[:notice] = "you can not edit quotes from other users"
      redirect_to user_path(current_user)
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
     flash.now[:danger] = "There was something wrong with your login information"
     render 'new'
   end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_login, except: [ :index, :show, :new, :create]
  before_action :require_same_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Happy Quoting #{@user.name}!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit

  end

  def update

    if @user.update(user_params)
      flash[:notice] = "Your account is updated succesfully!"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def show

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:notice] = "You can only edit your own profile"
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 50})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "img-circle")
  end

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/import_helper.rb
module ImportHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/imports/create.html.erb
<%= @quotes.each do |quote| %>
  <%= quote.source %>
  <%= quote.quote %>
<% end %>

app/views/imports/new.html.erb
<h1>test</h1>


<%= form_for :imports, url: imports_path do |f| %>

  <%= f.submit "IMPORT", class: 'btn btn-primary ' %>

<% end %>

app/views/imports/show.html.erb
<%= @quotes.each do |quote| %>
  <%= quote.source %>
  <%= quote.quote %>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Quotes', root_path, class: 'quote-text navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if logged_in? %>
        <ul class="nav navbar-nav navbar-left">
          <li class="nav-item"><%= link_to 'New Quote', new_quote_path, class: "nav-link btn btn-success" %></li>
          <li class="nav-item"><%= link_to 'Users', users_path, class: "nav-link" %></li>
          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li class="nav-item"><%= link_to 'Profile page', user_path(current_user), class: "nav-link" %></li>
              <li class="nav-item"><%= link_to 'Edit profile',edit_user_path(current_user),class: 'nav-link' %></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">

          <li class="nav-item"><%= link_to 'Log out',logout_path, method: :delete, class: 'nav-link' %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li class="nav-item"><%= link_to 'Sign up', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to ' Log in', login_path, class: 'nav-link' %></li>
        </ul>
      <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quotes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Sedgwick+Ave" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body class="color">
  <%= render 'layouts/nav' %>
  <div class="container">
    <%= flash_messages %>
  </div>

<%= yield %>

</body>
</html>

app/views/quotes/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h4><%= @quote.new_record? ? "Create a new Quote" : "Edit Youre Quote" %> </h4></div>
    <div class="panel-body">
      <%= simple_form_for @quote do |f| %>
        <%= f.input :quote, placeholder: 'Write your Quote' %>
        <%= f.input :source, placeholder: 'Enter the source where the quote comes from' %>
        <%= f.button :submit, class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/quotes/_quote.html.erb
<% obj.order("created_at DESC").each do |quote| %>
  <div class="panel panel-default">
    <div class="panel-heading">Created by: <%= quote.user.name  %></div>
      <div class="panel-body">
        <p class="quote-text text-center">
          "<%= quote.quote %>"
        </p>
        <br/>
        <p class="text-right"><em>source: <%= quote.source %></em></p>

      </div>
      <% if logged_in? && current_user == quote.user %>
        <div class="panel-footer">
          <%= link_to "Show Quote", quote_path(quote), class: "btn btn-success" %>
          <%= link_to "edit Quote", edit_quote_path(quote), class: "btn btn-warning" %>
          <%= link_to "Delete Quote", quote_path(quote), method: :delete, data: {confirm: "Are you sure to delete this quote?"}, class: "btn btn-danger" %>
        </div>
      <% end %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<div class="container">
  <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
    <%= render 'form' %>
  </div>
</div>

app/views/quotes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2" >
      <h2>This is a listing of all the quotes</h2>
      <%= render 'quote', obj: @quotes %>
    </div>
  </div>
</div>

app/views/quotes/new.html.erb
<div class="container">
  <div class="col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
    <%= render 'form' %>
  </div>
</div>

app/views/quotes/random_quote.html.erb
<div class="container">
  <div class="row">
    <% if @quote %>
    <div class="random-quote">
      <h1>" <%= @quote.quote %> "</h1>
      <h4 class="pull-right"><em>suorce: <%= @quote.source %> </em></h4>
    </div>
    <% else %>
      <p class="random-quote">
        It looks like there are no quotes in the database, so <%= link_to "sign up", signup_path %> and add quotes to the database
      </p>

    <% end %>
  </div>
</div>

<script type="text/javascript">
  var colors = ['#1abc9c', '#2ecc71','#3498db','#9b59b6','#34495e'];

  $('.color').css(
    "background-color", colors[
      Math.floor(
        Math.random()*colors.length
      )
    ]
  );
</script>

app/views/quotes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2" >
      <div class="panel panel-default">
        <div class="panel-heading">This is the Quote</div>
        <div class="panel-body">
          <p class="quote-text text-center">
            "<%= @quote.quote %>"
          </p>
          <br/>
          <p class="text-right"><em>source: <%= @quote.source %></em></p>
        </div>
        <% if logged_in? && current_user == @quote.user %>
          <div class="panel-footer">
            <%= link_to "edit Quote", edit_quote_path(@quote), class: "btn btn-warning" %>
            <%= link_to "Delete Quote", quote_path(@quote), method: :delete, data: {confirm: "Are you sure to delete this quote?"}, class: "btn btn-danger" %>

          </div>
        <% end %>
      </div>
      <% if logged_in? %>
        <div class="well">
          <%= link_to "Back to profile page", user_path(current_user) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><h4><%= @user.new_record? ? "Create a new Profile" : "Edit Youre Profile" %> </h4></div>
    <div class="panel-body">
      <%= simple_form_for @user do |f| %>
        <%= f.input :name, placeholder: 'Please enter your name' %>
        <%= f.input :email, placeholder: 'Please enter your email' %>
        <%= f.input :password, placeholder:(@user.new_record? ? 'Enter Password' : 'New password') %>
        <%= f.input :password_confirmation, placeholder:(@user.new_record? ? 'Enter Password' : 'Confirm new password') %>
        <%= f.submit(@user.new_record? ? "Sign up" : "update account", class: 'btn btn-primary ') %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class"row">
    <div class="col-md-8 col-md-offset-2">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <% @users.each do |user| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <div align="center">
              <%= link_to gravatar_for(user), user_path(user) %>
            <br>
              <%= user.name %>
            </div>
          </div>
          <div class="panel-body">
            <%= link_to "Show user page", user_path(user) %>
          </div>
          <div class="panel-footer">
            <p><%=user.name %> has <%= user.quotes.count %> Quotes </p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div align="center">
        <%= gravatar_for @user,size: 100  %>
        <h3> Welcome to <%= @user.name %> Quote page </h3>
      </div>
      <% if logged_in? && current_user == @user %>
        <div class="well">
          <%= link_to 'New Quote', new_quote_path, class: 'btn btn-success' %>
        </div>
      <% end %>

      <br>
        <%= render 'quotes/quote', obj: @user.quotes %>
    </div>
  </div>
</div>